name: Build ISO
on:
  push:
    branches:
      - master

jobs:
  build:
    runs-on: windows-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Download aria2 and ISOs (Windows 10 and 11 ISOs)
        run: |
          curl.exe -L https://github.com/aria2/aria2/releases/download/release-1.36.0/aria2-1.36.0-win-64bit-build1.zip -o "aria2.zip"
          Expand-Archive aria2.zip
          aria2\aria2-1.36.0-win-64bit-build1\aria2c.exe "https://archive.org/download/Windows10EnterpriseLTSC202164Bit/en-us_windows_10_enterprise_ltsc_2021_x64_dvd_d289cf96.iso" -o "Win10.iso" -x16 -s16
          aria2\aria2-1.36.0-win-64bit-build1\aria2c.exe "https://archive.org/download/windows-11-version-22h2/Win11_22H2_English_x64.iso" -o "Win11.iso" -x16 -s16
      - name: Set CI variable and run build script and print size
        run: |
          $env:CI = "true"
          powershell -File build.ps1
          Write-Host((Get-Item Bypass11_build_*.iso).length/1GB)
      - name: Release
        uses: softprops/action-gh-release@v1
        with:
          files: "Bypass11_build_*"
          token: ${{ github.token }}
          body: |
            This build is automatically generated through GitHub Actions and is English only. To get a different language ISO, please build this yourself.
            This commit was very kindly contributed by @${{ github.triggering_actor }}.
          prerelease: false
          tag_name: commit_${{ github.sha }}
          name: Bypass11 (commit ${{ github.sha }})
